from typing import TypedDict, Any


class ResearchState(TypedDict):
    # Original user request
    query: str

    # Entity we are investigating
    entity: dict[str, Any]

    # Current research round
    research_round: int

    # Maximum number of LLM research cycles
    max_research_rounds: int

    # Tools that have already been executed
    tools_executed: list[str]

    # Raw results returned by tools
    tool_results: list[dict[str, Any]]

    # Sources discovered during research
    sources: list[dict[str, Any]]

    # Facts/findings extracted from sources
    findings: list[dict[str, Any]]

    # Claims that need verification
    claims: list[dict[str, Any]]

    # Fields that are still missing
    missing_fields: list[str]

    # Conflicting pieces of information
    contradictions: list[dict[str, Any]]

    # Current research plan generated by the LLM
    research_plan: list[dict[str, Any]]

    # Whether entity validation succeeded
    entity_valid: bool

    # Whether final validation succeeded
    validation_passed: bool

    # Validation problems
    validation_errors: list[str]

    # Final structured result
    final_result: dict[str, Any] | None